### ISSUE TITLE
Replace Hide watched checkbox

### ISSUE THREAD

**Issue by OsaSoft** [OsaSoft/youtube-better-subscriptions#15]
The checkbox works, but its not exactly pretty. Replace it with a nice switch button thingy

**Comment by Drake37** [comment]
Hi! 
I have an idea. Do it without checkboxes, just fill with color.
example:
1) change html from
```html
<h2 class="yt-simple-endpoint style-scope ytd-compact-link-renderer subs-grid-menu-item">
    Hide watched
    <input id="osasoft-better-subscriptions_subs-grid" type="checkbox">
</h2>
```
to
```html
<label class="container-test">
	<input id="osasoft-better-subscriptions_subs-grid" type="checkbox">
	<h2 class="yt-simple-endpoint style-scope ytd-compact-link-renderer subs-grid-menu-item">
           Hide watched
        </h2>
</label>
```
2) add some css
```css
.container-test {
	height: 32px;
}
.container-test h2 {
	padding: 7px;
}
.container-test input {
	display: none;
}
.container-test input:checked ~h2{
	background: green;
}
.container-test:hover h2 {
	box-shadow: 0 0 2px 2px darkgrey;
}
```
